# Generated by Django 5.0.7 on 2024-08-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [("cinema", "0001_initial")]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("description", models.TextField()),
                ("duration", models.IntegerField()),
            ],
        ),
    ]
